// Generated by gencpp from file odom_client_server/diffodom.msg
// DO NOT EDIT!


#ifndef ODOM_CLIENT_SERVER_MESSAGE_DIFFODOM_H
#define ODOM_CLIENT_SERVER_MESSAGE_DIFFODOM_H

#include <ros/service_traits.h>


#include <odom_client_server/diffodomRequest.h>
#include <odom_client_server/diffodomResponse.h>


namespace odom_client_server
{

struct diffodom
{

typedef diffodomRequest Request;
typedef diffodomResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct diffodom
} // namespace odom_client_server


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::odom_client_server::diffodom > {
  static const char* value()
  {
    return "8c976f4f21b249dc4f54cfe66d6d9e4f";
  }

  static const char* value(const ::odom_client_server::diffodom&) { return value(); }
};

template<>
struct DataType< ::odom_client_server::diffodom > {
  static const char* value()
  {
    return "odom_client_server/diffodom";
  }

  static const char* value(const ::odom_client_server::diffodom&) { return value(); }
};


// service_traits::MD5Sum< ::odom_client_server::diffodomRequest> should match
// service_traits::MD5Sum< ::odom_client_server::diffodom >
template<>
struct MD5Sum< ::odom_client_server::diffodomRequest>
{
  static const char* value()
  {
    return MD5Sum< ::odom_client_server::diffodom >::value();
  }
  static const char* value(const ::odom_client_server::diffodomRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::odom_client_server::diffodomRequest> should match
// service_traits::DataType< ::odom_client_server::diffodom >
template<>
struct DataType< ::odom_client_server::diffodomRequest>
{
  static const char* value()
  {
    return DataType< ::odom_client_server::diffodom >::value();
  }
  static const char* value(const ::odom_client_server::diffodomRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::odom_client_server::diffodomResponse> should match
// service_traits::MD5Sum< ::odom_client_server::diffodom >
template<>
struct MD5Sum< ::odom_client_server::diffodomResponse>
{
  static const char* value()
  {
    return MD5Sum< ::odom_client_server::diffodom >::value();
  }
  static const char* value(const ::odom_client_server::diffodomResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::odom_client_server::diffodomResponse> should match
// service_traits::DataType< ::odom_client_server::diffodom >
template<>
struct DataType< ::odom_client_server::diffodomResponse>
{
  static const char* value()
  {
    return DataType< ::odom_client_server::diffodom >::value();
  }
  static const char* value(const ::odom_client_server::diffodomResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ODOM_CLIENT_SERVER_MESSAGE_DIFFODOM_H
